Repository emberjs/ember.js, pull requests merged in 2019-11, with the labels that each got.

#18463 [DOC] #18228 Add example to EmberArray.forEach documentation
  packages/@ember/-internals/runtime/lib/mixins/array.js
Labels: Needs Submitter Response

#17834 [BUGFIX beta] Prevents autotracking ArrayProxy creation
  packages/@ember/-internals/glimmer/tests/integration/components/tracked-test.js
  packages/@ember/-internals/metal/lib/array.ts
  packages/@ember/-internals/metal/lib/property_get.ts
  packages/@ember/-internals/metal/lib/tracked.ts
  packages/@ember/-internals/metal/tests/accessors/get_test.js
  packages/@ember/-internals/metal/tests/tracked/validation_test.js
  packages/@ember/-internals/runtime/lib/mixins/array.js
  packages/@ember/-internals/runtime/lib/system/array_proxy.js
Labels: Octane

#18337 [DOC] Octanify glimmer syntax documentation
  packages/@ember/-internals/glimmer/index.ts
  packages/@ember/-internals/glimmer/lib/helpers/each-in.ts
  packages/@ember/-internals/glimmer/lib/helpers/get.ts
  packages/@ember/-internals/glimmer/lib/helpers/if-unless.ts
  packages/@ember/-internals/glimmer/lib/helpers/unbound.ts
  packages/@ember/-internals/glimmer/lib/syntax/outlet.ts
Labels: Documentation, Octane
