Repository emberjs/ember.js, pull requests merged in 2020-04, with the labels that each got.

#18861 [BUGFIX release] Update glimmer-vm to 0.50.1 to improve dev time performance.
  package.json
  packages/@ember/-internals/glimmer/tests/utils/backtracking-rerender.js
  yarn.lock
Labels: Bug

#18353 [BUGFIX beta] improve `fn` & `on` undefined callback message
  packages/@ember/-internals/glimmer/lib/helpers/fn.ts
  packages/@ember/-internals/glimmer/lib/modifiers/on.ts
  packages/@ember/-internals/glimmer/tests/integration/helpers/fn-test.js
Labels: Needs Submitter Response

#18869 [BUGFIX release] Update to glimmer-vm 0.50.2.
  package.json
  yarn.lock
Labels: Bug

#18871 [BUGFIX beta] Make assertions from `on` and `fn` more actionable.
  packages/@ember/-internals/glimmer/lib/helpers/fn.ts
  packages/@ember/-internals/glimmer/lib/modifiers/on.ts
  packages/@ember/-internals/glimmer/lib/renderer.ts
  packages/@ember/-internals/glimmer/lib/resolver.ts
  packages/@ember/-internals/glimmer/tests/integration/helpers/fn-test.js
  packages/@ember/-internals/glimmer/tests/integration/modifiers/on-test.js
Labels: Bug

#18183 Correct property name in @union cp example
  packages/@ember/object/lib/computed/reduce_computed_macros.js
Labels: Documentation

#18879 [BUGFIX lts] Update glimmer-vm to fixes knock on errors during cleanup.
  package.json
  yarn.lock
Labels: Bug

#18878 [BUGFIX lts] Update glimmer-vm to 0.50.4 (fixes knock on errors during cleanup).
  package.json
  packages/@ember/-internals/glimmer/tests/integration/application/rendering-test.js
  packages/@ember/-internals/glimmer/tests/integration/mount-test.js
  yarn.lock
Labels: Bug

#18913 [BUGFIX release] Update to glimmer-vm 0.51.0.
  package.json
  yarn.lock
Labels: internal

#18927 [FEATURE EMBER_GLIMMER_IN_ELEMENT] Enable by default.
  packages/@ember/canary-features/index.ts
Labels: enhancement

#18926 [FEATURE EMBER_NAMED_BLOCKS] Enable by default.
  packages/@ember/canary-features/index.ts
Labels: enhancement
