Repository emberjs/ember.js, pull requests merged in 2020-08, with the labels that each got.

#19072 [BUGFIX release] Update to glimmerjs/glimmer-vm 0.55.3.
  package.json
  yarn.lock
Labels: internal

#19075 integration/components/life-cycle: fix removeComponent
  packages/@ember/-internals/glimmer/tests/integration/components/life-cycle-test.js
Labels: internal

#19085 Ensure ESLint plugins use the correct `tsconfig.json`
  .eslintrc.js
Labels: internal

#19086 Pass transition object to activate/deactivate hooks and events
  packages/@ember/-internals/routing/lib/system/route.ts
  packages/ember/tests/routing/decoupled_basic_test.js
Labels: enhancement

#19087 [BUGFIX beta] Pass resolver to Test app in generated initializer test
  blueprints/initializer-test/qunit-rfc-232-files/__root__/__testType__/__path__/__name__-test.js
  blueprints/instance-initializer-test/qunit-rfc-232-files/__root__/__testType__/__path__/__name__-test.js
  node-tests/fixtures/initializer-test/module-unification/rfc232.js
  node-tests/fixtures/initializer-test/rfc232.js
  node-tests/fixtures/instance-initializer-test/module-unification/rfc232.js
  node-tests/fixtures/instance-initializer-test/rfc232.js
Labels: Bug

#19106 [BUGFIX lts] Ensure `destroy` methods on `CoreObject` are invoked.
  packages/@ember/-internals/runtime/lib/system/core_object.js
  packages/@ember/-internals/runtime/tests/mixins/container_proxy_test.js
  packages/@ember/-internals/runtime/tests/system/core_object_test.js
  packages/@ember/application/tests/reset_test.js
Labels: Bug
