Repository emberjs/ember.js, pull requests merged in 2020-09, with the labels that each got.

#19119 [REFACTOR] Removes AoT mode
  package.json
  packages/@ember/-internals/glimmer/lib/compile-time-lookup.ts
  packages/@ember/-internals/glimmer/lib/component-managers/curly.ts
  packages/@ember/-internals/glimmer/lib/component-managers/custom.ts
  packages/@ember/-internals/glimmer/lib/component-managers/internal.ts
  packages/@ember/-internals/glimmer/lib/component-managers/mount.ts
  packages/@ember/-internals/glimmer/lib/component-managers/outlet.ts
  packages/@ember/-internals/glimmer/lib/component-managers/root.ts
  packages/@ember/-internals/glimmer/lib/component-managers/template-only.ts
  packages/@ember/-internals/glimmer/lib/renderer.ts
  packages/@ember/-internals/glimmer/lib/resolver.ts
  packages/@ember/-internals/glimmer/lib/syntax.ts
  yarn.lock
Labels: internal

#19122 [BUGFIX] Prevent dynamic invocations
  package.json
  yarn.lock
Labels: Bug

#19124 Fix rendering engine usage within a `fastboot` sandbox
  .eslintrc.js
  package.json
  tests/node/component-rendering-test.js
  tests/node/fastboot-sandbox-test.js
  tests/node/helpers/load-ember.js
  yarn.lock
Labels: Bug

#19125 Fix rendering engine usage within a `fastboot` sandbox
  .eslintrc.js
  package.json
  tests/node/component-rendering-test.js
  tests/node/fastboot-sandbox-test.js
  tests/node/helpers/load-ember.js
  yarn.lock
Labels: Bug

#19136 Update router microlib to improve Transition related debugging.
  package.json
  packages/@ember/-internals/routing/lib/system/transition.ts
  tests/docs/expected.js
  yarn.lock
Labels: enhancement

#19150 [CLEANUP] Remove EMBER_CUSTOM_COMPONENT_ARG_PROXY feature
  packages/@ember/-internals/glimmer/lib/component-managers/custom.ts
  packages/@ember/-internals/glimmer/tests/integration/components/tracked-test.js
  packages/@ember/canary-features/index.ts
Labels: internal

#19163 [BUGFIX beta] Use args proxy for modifier managers.
  packages/@ember/-internals/glimmer/lib/component-managers/custom.ts
  packages/@ember/-internals/glimmer/lib/modifiers/custom.ts
  packages/@ember/-internals/glimmer/lib/utils/args-proxy.ts
  packages/@ember/-internals/glimmer/tests/integration/components/angle-bracket-invocation-test.js
  packages/@ember/-internals/glimmer/tests/integration/custom-component-manager-test.js
  packages/@ember/-internals/glimmer/tests/integration/custom-modifier-manager-test.js
Labels: Bug
