Repository emberjs/ember.js, pull requests merged in 2020-07, with the labels that each got.

#19054 Remove `_viewRegistry` injection to `view`
  packages/@ember/application/tests/application_test.js
  packages/@ember/engine/index.js
  packages/@ember/engine/tests/engine_test.js
  packages/internal-test-helpers/lib/test-cases/rendering.js
Labels: internal

#19056 [BUGFIX release] Update glimmer-vm to 0.54.2.
  package.json
  yarn.lock
Labels: Bug

#19059 [BUGFIX lts] Prevent `<base target="_parent">` from erroring in HistoryLocation
  packages/@ember/-internals/routing/lib/location/history_location.ts
  packages/@ember/-internals/routing/tests/location/history_location_test.js
Labels: Bug

#19062 [FEATURE] Add @ember/destroyable feature.
  packages/@ember/canary-features/index.ts
  packages/@ember/destroyable/index.ts
  packages/ember/index.js
  tests/docs/expected.js
Labels: enhancement

#19067 [FEATURE] Enable @glimmer/tracking/primitives/cache APIs.
  packages/@ember/canary-features/index.ts
Labels: enhancement

#19068 [FEATURE] Enable @ember/destroyable API.
  packages/@ember/canary-features/index.ts
Labels: enhancement
