Repository emberjs/ember.js, pull requests merged in 2020-01, with the labels that each got.

#18471 [DOC] Update explanation of router service `isActive` method and add code example
  packages/@ember/-internals/routing/lib/services/router.ts
Labels: Needs Submitter Response

#17923 replaceWith explaination changes
  packages/@ember/-internals/routing/lib/services/router.ts
Labels: Documentation

#18596 [DOCS] Route, setupController: add missing transition param
  packages/@ember/-internals/routing/lib/system/route.ts
Labels: Needs Team Response
