Repository emberjs/ember.js, pull requests merged in 2020-05, with the labels that each got.

#18958 [BUGFIX release] Ensure AST transforms using `in-element` work properly.
  package.json
  packages/ember-template-compiler/lib/plugins/transform-in-element.ts
  yarn.lock
Labels: Bug

#18925 [DOC] Update references to Ember.View in documentation
  packages/@ember/-internals/runtime/lib/system/core_object.js
Labels: Documentation

#18982 [BUGFIX release] Update glimmer-vm packages to 0.53.0
  package.json
  packages/@ember/-internals/glimmer/lib/component-managers/custom.ts
  packages/@ember/-internals/glimmer/lib/component-managers/input.ts
  packages/@ember/-internals/glimmer/lib/helpers/action.ts
  packages/@ember/-internals/glimmer/lib/helpers/get.ts
  yarn.lock
Labels: Bug

#18980 Configures Issue Templates for the repository.
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-documentation-issue-report.md
  .github/ISSUE_TEMPLATE/3-feature-request.md
  .github/ISSUE_TEMPLATE/4-other.md
Labels: Documentation, Needs Team Response

#17571 [BUGFIX] avoid tampering `queryParam` argument in RouterService#isActive
  packages/@ember/-internals/routing/lib/services/router.ts
  packages/ember/tests/routing/router_service_test/isActive_test.js
Labels: Query Params, Routing
