Repository emberjs/ember.js, pull requests merged in 2021-02, with the labels that each got.

#19370 [BUGFIX beta] Update glimmer-vm to prevent errors for older inline precompilation
  package.json
  yarn.lock
Labels: Bug

#19345 [RFC 698] Deprecate `<LinkTo>` positional arguments
  packages/@ember/-internals/glimmer/lib/components/link-to.ts
  packages/@ember/-internals/glimmer/lib/helpers/query-param.ts
  packages/@ember/-internals/glimmer/tests/integration/application/engine-test.js
  packages/@ember/-internals/glimmer/tests/integration/components/link-to/query-params-curly-test.js
  packages/@ember/-internals/glimmer/tests/integration/components/link-to/rendering-curly-test.js
  packages/@ember/-internals/glimmer/tests/integration/components/link-to/routing-angle-test.js
  packages/@ember/-internals/glimmer/tests/integration/components/link-to/routing-curly-test.js
  packages/@ember/-internals/glimmer/tests/integration/components/link-to/transitioning-classes-curly-test.js
  packages/ember-template-compiler/lib/plugins/transform-link-to.ts
  packages/ember-template-compiler/tests/plugins/transform-link-to-test.js
  packages/ember-testing/tests/acceptance_test.js
  packages/ember/tests/routing/query_params_test.js
  packages/ember/tests/routing/query_params_test/model_dependent_state_with_query_params_test.js
  packages/ember/tests/routing/query_params_test/query_param_async_get_handler_test.js
  packages/ember/tests/routing/query_params_test/query_params_paramless_link_to_test.js
  packages/ember/tests/routing/query_params_test/shared_state_test.js
Labels: Deprecation, Help Wanted

#19396 [BUGFIX release] Revert deprecation of htmlSafe and isHTMLSafe
  packages/ember/index.js
  packages/ember/tests/reexports_test.js
Labels: Bug

#19399 Update ArrayProxy Documentation
  packages/@ember/-internals/runtime/lib/system/array_proxy.js
Labels: Documentation

#19407 Add deprecation for `Route#disconnectOutlet`
  packages/@ember/-internals/glimmer/tests/integration/application/debug-render-tree-test.ts
  packages/@ember/-internals/routing/lib/system/route.ts
  packages/ember/tests/routing/template_rendering_test.js
  packages/internal-test-helpers/index.js
  packages/internal-test-helpers/lib/ember-dev/deprecation.ts
Labels: Deprecation

#19429 [DEPRECATE] `registerPlugin` / `unregisterPlugin` and legacy class based AST plugins
  packages/ember-template-compiler/lib/system/compile-options.ts
  packages/ember-template-compiler/tests/system/compile_options_test.js
Labels: Deprecation
