Repository emberjs/ember.js, pull requests merged in 2021-03, with the labels that each got.

#19433 Add deprecation for `Route#renderTemplate`
  packages/@ember/-internals/glimmer/tests/integration/application/debug-render-tree-test.ts
  packages/@ember/-internals/glimmer/tests/integration/application/rendering-test.js
  packages/@ember/-internals/routing/lib/system/route.ts
  packages/ember-testing/tests/acceptance_test.js
  packages/ember/tests/routing/decoupled_basic_test.js
  packages/ember/tests/routing/model_loading_test.js
  packages/ember/tests/routing/template_rendering_test.js
Labels: Deprecation

#19442 Add deprecation for `Route#render` method
  packages/@ember/-internals/glimmer/tests/integration/application/debug-render-tree-test.ts
  packages/@ember/-internals/glimmer/tests/integration/application/rendering-test.js
  packages/@ember/-internals/routing/lib/system/route.ts
  packages/ember/tests/routing/model_loading_test.js
  packages/ember/tests/routing/template_rendering_test.js
  tests/docs/expected.js
Labels: Deprecation

#19445 Setup git user in alpha publishing script.
  .github/workflows/alpha-releases.yml
Labels: internal

#19446 [DOC] Add rendered output of each-in helper
  packages/@ember/-internals/glimmer/lib/helpers/each-in.ts
Labels: Documentation

#19448 Ensure query params are preserved through an intermediate loading state transition
  package.json
  packages/ember/tests/routing/substates_test.js
  yarn.lock
Labels: Bug

#19458 Refactor router: remove owner presence checks
  packages/@ember/-internals/routing/lib/system/router.ts
  packages/@ember/-internals/routing/tests/system/dsl_test.js
  packages/@ember/-internals/routing/tests/system/router_test.js
Labels: internal

#19477 [BUGFIX LTS] move LinkTo assertion into a method so LinkToExternal can override
  packages/@ember/-internals/glimmer/lib/components/-link-to.ts
  tests/docs/expected.js
Labels: Bug
