Repository emberjs/ember.js, pull requests merged in 2022-10, with the labels that each got.

#20189 [DOC] moving comment docs to interface methods – `Evented`
  packages/@ember/object/evented.ts
Labels: Documentation, TypeScript

#20218 [BUGFIX beta] Remove `Function` and `String` from `EXTEND_PROTOTYPES` type
  types/preview/ember/index.d.ts
Labels: TypeScript

#20235 [BUGFIX beta] update `@types/node` for TS 4.9 issue
  package.json
  yarn.lock
Labels: Bug, dependencies, TypeScript

#20175 Convert packages/ember to TS
  packages/@ember/-internals/environment/lib/context.ts
  packages/@ember/-internals/error-handling/index.ts
  packages/@ember/-internals/glimmer/index.ts
  packages/@ember/-internals/glimmer/lib/helper.ts
  packages/@ember/-internals/glimmer/lib/template_registry.ts
  packages/@ember/helper/type-tests/invoke-helper.test.ts
  packages/ember/index.js
  packages/ember/index.ts
  packages/ember/type-tests/ember.test.ts
  packages/internal-test-helpers/lib/test-cases/rendering.ts
  packages/internal-test-helpers/lib/test-cases/router-non-application.ts
  packages/internal-test-helpers/lib/test-cases/test-resolver-application.ts
  packages/loader/lib/index.d.ts
Labels: TypeScript
