Repository emberjs/ember.js, pull requests merged in 2022-11, with the labels that each got.

#20256 [BUGFIX release] Correct types for Ember Arrays
  packages/@ember/-internals/glimmer/lib/utils/iterator.ts
  packages/@ember/-internals/utils/lib/ember-array.ts
  packages/@ember/-internals/utils/types.ts
  packages/@ember/array/index.ts
  packages/@ember/array/type-tests/index.ts
  packages/@ember/array/type-tests/mutable.ts
  packages/@ember/debug/data-adapter.ts
  type-tests/preview/@ember/array-test/array.ts
  type-tests/preview/ember/array.ts
  type-tests/preview/ember/ember-module-tests.ts
  type-tests/preview/ember/ember-tests.ts
  types/preview/@ember/array/-private/native-array.d.ts
  types/preview/@ember/array/index.d.ts
  types/preview/@ember/array/mutable.d.ts
  types/preview/ember/-private/type-utils.d.ts
Labels: Bug, TypeScript

#20188 Use service registry in owner.lookup
  type-tests/preview/@ember/owner-tests.ts
  types/preview/@ember/owner/index.d.ts
Labels: TypeScript

#20268 [CLEANUP] Make intern utility type safe
  packages/@ember/-internals/utils/lib/intern.ts
Labels: TypeScript

#20270 [FEATURE] Introduce new `@ember/routing` sub-modules (RFC 0821)
  packages/@ember/routing/route-info.ts
  packages/@ember/routing/transition.ts
  types/preview/@ember/routing/route-info.d.ts
Labels: TypeScript

#20272 [DOC] Add documentation for RFC 0821 items
  packages/@ember/-internals/owner/index.ts
  packages/@ember/-internals/runtime/lib/mixins/container_proxy.ts
  packages/@ember/-internals/runtime/lib/mixins/registry_proxy.ts
  packages/@ember/owner/index.ts
  packages/@ember/routing/lib/route-info.ts
  packages/@ember/routing/lib/transition.ts
  packages/@ember/routing/route-info.ts
  packages/@ember/routing/transition.ts
  tests/docs/expected.js
Labels: Documentation, TypeScript

#20275 [FEATURE] Stable types infra
  .gitattributes
  .gitignore
  package.json
  packages/@ember/object/-internals.ts
  packages/@ember/object/core.ts
  tsconfig.json
  tsconfig/compiler-options.json
  tsconfig/publish-types.json
  types/preview/index.d.ts
  types/publish.mjs
  types/stable/index.d.ts
  yarn.lock
Labels: TypeScript

#20280 Don't double-run `tsc` for generating types
  package.json
Labels: internal, TypeScript

#20283 [BUGFIX beta] revert TS `compilerOptions.target` to ES2017
  tsconfig/compiler-options.json
Labels: Bug

#20285 Update to TS v4.9
  package.json
  yarn.lock
Labels: internal, TypeScript
