Repository emberjs/ember.js, pull requests merged in 2022-12, with the labels that each got.

#20310 Replace most `InternalOwner` uses with `Owner`
  packages/@ember/component/type-tests/helper/index.test.ts
  packages/@ember/component/type-tests/set-component-manager.test.ts
  packages/@ember/controller/type-tests/index.test.ts
  packages/@ember/debug/container-debug-adapter.ts
  packages/@ember/debug/data-adapter.ts
  packages/@ember/debug/lib/capture-render-tree.ts
  packages/@ember/engine/instance.ts
  packages/@ember/engine/type-tests/instance.test.ts
  packages/@ember/object/type-tests/core/index.test.ts
  packages/@ember/object/type-tests/ember-object.test.ts
  packages/@ember/object/type-tests/events/index.test.ts
  packages/@ember/routing/route.ts
  packages/@ember/routing/router.ts
  packages/@ember/routing/type-tests/auto-location.test.ts
  packages/@ember/routing/type-tests/hash-location.test.ts
  packages/@ember/routing/type-tests/history-location.test.ts
  packages/@ember/routing/type-tests/none-location.test.ts
  packages/@ember/routing/type-tests/route/index.test.ts
  packages/@ember/routing/type-tests/route/overrides.test.ts
  packages/@ember/routing/type-tests/route/query-params.test.ts
  packages/@ember/routing/type-tests/route/send.test.ts
  packages/@ember/routing/type-tests/router-service.test.ts
  packages/@ember/routing/type-tests/router/index.test.ts
  packages/@ember/service/type-tests/index.test.ts
Labels: internal, TypeScript

#20313 Remove runtime dependence on `InternalOwner`
  packages/@ember/routing/router.ts
  packages/internal-test-helpers/lib/registry-check.ts
Labels: internal, TypeScript

#20316 Reimplement publish-types script with recast
  package.json
  packages/@ember/-internals/owner/index.ts
  types/publish.mjs
  yarn.lock
Labels: internal, TypeScript

#20318 [BUGFIX LTS] Backport `Resolver` to preview types
  types/preview/@ember/owner/index.d.ts
Labels: Bug, TypeScript

#20321 [BUGFIX LTS] ContainerDebugAdapter extends EmberObject
  types/preview/@ember/debug/container-debug-adapter.d.ts
Labels: Bug, TypeScript

#20323 [FEATURE] Introduce stable types for `@ember/error`
  types/preview/@ember/error/index.d.ts
  types/preview/index.d.ts
  types/publish.mjs
Labels: enhancement, TypeScript

#20324 Fix more bugs in type publishing infra
  packages/@ember/debug/lib/deprecate.ts
  packages/internal-test-helpers/lib/ember-dev/assertion.ts
  packages/internal-test-helpers/lib/ember-dev/deprecation.ts
  packages/internal-test-helpers/lib/ember-dev/warning.ts
  types/publish.mjs
Labels: internal, TypeScript

#20322 Update lint dependencies
  .eslintrc.js
  package.json
  yarn.lock
Labels: dependencies, internal

#20326 Types: simplify internal views/states modules
  packages/@ember/-internals/views/lib/views/states.ts
  packages/@ember/-internals/views/lib/views/states/default.ts
  packages/@ember/-internals/views/lib/views/states/destroying.ts
  packages/@ember/-internals/views/lib/views/states/has_element.ts
  packages/@ember/-internals/views/lib/views/states/in_dom.ts
  packages/@ember/-internals/views/lib/views/states/pre_render.ts
Labels: internal, TypeScript

#20327 Fix the types for the mutation-methods of `NativeArray`
  types/preview/@ember/array/-private/native-array.d.ts
Labels: Bug, TypeScript

#20331 Bugfix/internal: more cases in types publishing infra
  types/publish.mjs
Labels: internal, TypeScript

#20332 Types publishing: always `this.traverse(path)` in visitors
  types/publish.mjs
Labels: internal, TypeScript
