Repository emberjs/ember.js, pull requests merged in 2022-09, with the labels that each got.

#20194 [BUGFIX beta] Provide a `.d.ts` file at types/stable
  types/stable/index.d.ts
Labels: Bug, TypeScript

#20196 [BUGFIX beta] types imports are at 'ember-source/types'
  package.json
  types/stable/index.d.ts
Labels: Bug, TypeScript

#20202 [DOC] Reformat API docs for Typescript - @ember/controller
  packages/@ember/controller/index.ts
Labels: Documentation, TypeScript

#20192 [DOC] Reformatting Ember API docs for Typescript - proxy-mixin-interface
  packages/@ember/object/promise-proxy-mixin.ts
Labels: Documentation, TypeScript

#20199 [DOC] Format API docs for Typescript - @ember/array
  packages/@ember/array/index.ts
  packages/@ember/array/proxy.ts
Labels: Documentation, TypeScript

#20204 [FEATURE] Test all supported TS versions in CI
  .github/workflows/ci.yml
  .github/workflows/night-ts.yml
  package.json
  packages/@ember/debug/data-adapter.ts
  packages/@ember/routing/route.ts
  yarn.lock
Labels: TypeScript

#20212 [BUGFIX beta] remove wrong exports from preview routing types
  types/preview/@ember/application/index.d.ts
  types/preview/@ember/routing/index.d.ts
Labels: Bug, TypeScript
