Repository emberjs/ember.js, pull requests merged in 2023-03, with the labels that each got.

#20398 [BUGFIX LTS] Fix runloop types on TS 5.0+
  packages/@ember/runloop/index.ts
Labels: Bug, TypeScript

#20381 [CLEANUP] Remove deprecated `@ember/string` package
  packages/@ember/routing/router-service.ts
  packages/@ember/string/index.ts
  packages/@ember/string/lib/string_registry.ts
  packages/@ember/string/tests/camelize_test.js
  packages/@ember/string/tests/capitalize_test.js
  packages/@ember/string/tests/classify_test.js
  packages/@ember/string/tests/dasherize_test.js
  packages/@ember/string/tests/decamelize_test.js
  packages/@ember/string/tests/underscore_test.js
  packages/@ember/string/tests/w_test.js
  packages/ember/index.ts
  packages/ember/tests/reexports_test.js
  tests/docs/expected.js
  type-tests/@ember/string-tests.ts
  type-tests/ember/ember-module-tests.ts
  type-tests/ember/ember-tests.ts
  type-tests/ember/string.ts
  types/preview/@ember/string/index.d.ts
  types/preview/ember/index.d.ts
  types/preview/index.d.ts
Labels: Cleanup

#20380 [CLEANUP] Remove deprecated `assign` polyfill
  ember-cli-build.js
  packages/@ember/polyfills/index.ts
  packages/@ember/polyfills/lib/assign.ts
  packages/@ember/polyfills/tests/assign_test.js
  packages/@ember/polyfills/type-tests/assign.test.ts
  packages/ember/index.ts
  packages/ember/tests/reexports_test.js
  tests/docs/expected.js
  type-tests/@ember/polyfills-tests.ts
  type-tests/ember/ember-module-tests.ts
  type-tests/ember/utils.ts
  types/preview/@ember/polyfills/index.d.ts
  types/preview/@ember/polyfills/types.d.ts
  types/preview/ember/index.d.ts
  types/preview/index.d.ts
  types/publish.mjs
Labels: Cleanup

#20379 [CLEANUP] Remove deprecated `@ember/error` package
  ember-cli-build.js
  packages/@ember/error/index.ts
  packages/@ember/error/tests/index_test.js
  packages/@ember/error/type-tests/index.test.ts
  packages/ember/index.ts
  packages/ember/tests/reexports_test.js
  smoke-tests/ember-test-app/.eslintignore
  smoke-tests/ember-test-app/.eslintrc.js
  smoke-tests/ember-test-app/.gitignore
  smoke-tests/ember-test-app/.prettierignore
  smoke-tests/ember-test-app/.watchmanconfig
  smoke-tests/ember-test-app/app/index.html
  smoke-tests/ember-test-app/config/ember-cli-update.json
  smoke-tests/ember-test-app/config/environment.js
  smoke-tests/ember-test-app/config/targets.js
  smoke-tests/ember-test-app/ember-cli-build.js
  smoke-tests/ember-test-app/package.json
  smoke-tests/ember-test-app/tests/helpers/.gitkeep
  smoke-tests/ember-test-app/tests/helpers/index.js
  smoke-tests/ember-test-app/tests/index.html
  type-tests/@ember/error-tests.ts
  type-tests/ember/ember-module-tests.ts
  type-tests/ember/error.ts
  types/preview/ember/index.d.ts
Labels: Cleanup

#20414 [CLEANUP] Add @ember/string to smoke-tests app
  smoke-tests/ember-test-app/package.json
Labels: Cleanup

#20415 [CLEANUP] Remove unused imports
  packages/ember/index.ts
Labels: Cleanup

#20417 Fix types for `Location` after deprecation removal
  .github/workflows/ci.yml
  packages/@ember/routing/hash-location.ts
  packages/@ember/routing/history-location.ts
  packages/@ember/routing/location.ts
  packages/@ember/routing/none-location.ts
  packages/@ember/routing/router.ts
  packages/@ember/routing/type-tests/location.test.ts
  packages/@ember/routing/type-tests/router-service.test.ts
  packages/@ember/routing/type-tests/router/index.test.ts
  type-tests/@ember/routing-test/hash-location.test.ts
  type-tests/@ember/routing-test/history-location.test.ts
  type-tests/@ember/routing-test/location.test.ts
  type-tests/@ember/routing-test/none-location.test.ts
  types/preview/@ember/routing/hash-location.d.ts
  types/preview/@ember/routing/history-location.d.ts
  types/preview/@ember/routing/location.d.ts
  types/preview/@ember/routing/none-location.d.ts
  types/preview/index.d.ts
Labels: TypeScript
